spring.application.name=catalogo-negocio

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalogo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=${SPRING_MULTIPART_MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${SPRING_MULTIPART_MAX_REQUEST_SIZE:5MB}

app.upload-dir=${APP_UPLOAD_DIR:uploads}
app.whatsapp-number=${APP_WHATSAPP_NUMBER:573042460511}
app.business-name=${APP_BUSINESS_NAME:Aluminio Y Acero DJD Y Asociados}
app.logo-path=${APP_LOGO_PATH:/img/logo.jpg}
app.about-title=${APP_ABOUT_TITLE:Soluciones en aluminio, acero y vidrio para hogares y negocios}
app.about-text=${APP_ABOUT_TEXT:Fabricamos puertas abatibles, puertas corredizas, ventanas, mamparas para bano, barandas en acero, muebles para cocina, espejos y estructuras metalicas con instalacion profesional y atencion personalizada.}
app.social-instagram=${APP_SOCIAL_INSTAGRAM:https://www.instagram.com/aluminioacerodjd/}
app.social-facebook=${APP_SOCIAL_FACEBOOK:https://www.facebook.com/aluminio.acero.djd.asociados}
app.admin-registration-enabled=${APP_ADMIN_REGISTRATION_ENABLED:false}
